### PR TITLE
Bulk account creation

### PR DESCRIPTION
**Pull request by cycomachead**
Support Bulk Account Creation for logged in users. 

POST format:

```json:
{ 
"users": [
{
"username": "user1", "password": "password1", "email": 'OPTIONAL'
},
{ ...}
]
}
```

If an email is not provided, then the current user's email address is used. 
To be able to use this route, you must either be an admin OR have `is_teacher` set to true on your account.
This flag is probably not a permanent solution, but could work to solve immediate issues. 

* users are auto marked as verified, and we skip a welcome email
* We do track who created the user
* no UI for any of this right now. 
* We check to make sure no users exist first, otherwise use a transaction when creating accounts.

### CODE REVIEW

**Comment by bromagosa** [comment]
This looks beautiful, Michael! So glad you seem to have some time for the cloud again! :D

**Comment by bromagosa** [comment]
Hmm... the migration script seems to be broken. Here's what running it on staging spits out:

```
/usr/bin/lua5.1: ...al/share/lua/5.1/lapis/cmd/nginx/attached_server.lua:72: Failed to exec code on server, got: 401

<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>openresty/1.21.4.1</center>
</body>
</html>

stack traceback:
        [C]: in function 'error'
        ...al/share/lua/5.1/lapis/cmd/nginx/attached_server.lua:72: in function 'exec'
        /usr/local/share/lua/5.1/lapis/cmd/actions.lua:288: in function </usr/local/share/lua/5.1/lapis/cmd/actions.lua:272>
        (tail call): ?
        (tail call): ?
        (tail call): ?
        ...local/lib/luarocks/rocks-5.1/lapis/1.9.0-1/bin/lapis:4: in main chunk
        [C]: ?

```

Trying it again times out:

```
Using temporary server...
/usr/bin/lua5.1: ...sr/local/share/lua/5.1/lapis/cmd/attached_server.lua:40: Timed out waiting for server to open (9.3636088371277)
stack traceback:
        [C]: in function 'error'
        ...sr/local/share/lua/5.1/lapis/cmd/attached_server.lua:40: in function <...sr/local/share/lua/5.1/lapis/cmd/attached_server.lua:12>
        (tail call): ?
        (tail call): ?
        /usr/local/share/lua/5.1/lapis/cmd/nginx.lua:143: in function </usr/local/share/lua/5.1/lapis/cmd/nginx.lua:140>
        (tail call): ?
        /usr/local/share/lua/5.1/lapis/cmd/actions.lua:287: in function </usr/local/share/lua/5.1/lapis/cmd/actions.lua:272>
        (tail call): ?
        (tail call): ?
        (tail call): ?
        ...local/lib/luarocks/rocks-5.1/lapis/1.9.0-1/bin/lapis:4: in main chunk
        [C]: ?

```

**Comment by bromagosa** [comment]
Additionally, the changes to `nginx.conf` seem to mess up the SSL config, and the site doesn't load at all.

**Comment by bromagosa** [comment]
Rolling back the `nginx.conf` and `nginx.conf.d` changes makes the site work again. Can we defer these changes for some other time (or not implement them at all)?

**Comment by bromagosa** [comment]
Except now the Staging certs are expired and I can't get them to update, neither using the `renew-certs` script or by manually running `certbot certonly --webroot -w /home/cloud/snapCloud/html/ -d staging.snap.berkeley.edu --config-dir=lets-encrypt --logs-dir=lets-encrypt --work-dir=lets-encrypt`... HALP :)

**Comment by bromagosa** [comment]
Sorry about the spam. Apparently, migrations work locally but not on neither servers. Hmm... maybe something to do with the new pgbouncer setup?

**Comment by cycomachead** [comment]
The staging server when it was setup never got certbot installed. That may be the problem. For migrations - let me see what’s up later today I think you need to run the script in bin/ and weMight need to update lapis as there was a bug which I think was fixed in recent versions about reading the right environment. -- Michael BallFrom my iPhonemichaelball.coOn Apr 12, 2023, at 3:23 AM, Bernat Romagosa ***@***.***> wrote:﻿
Sorry about the spam. Apparently, migrations work locally but not on neither servers. Hmm... maybe something to do with the new pgbouncer setup?

**Comment by bromagosa** [comment]
Updated Lapis to 1.13.1, and both the `bin/lapis-migrate` script and the `lapis migrate` fail to connect to postgres.

**Pull request merged**
