### PR TITLE
Remove rollbar exception tracking

### PR DESCRIPTION
**Pull request by cycomachead**
To be merged/deployed after Sentry is all working correctly.

### CODE REVIEW

**Comment by cycomachead** [comment]
@bromagosa I am going to merge this in a day or two. Can you pull and tell me if this works locally for you?

**Comment by bromagosa** [comment]
I got an error about "raven not found". I tried to figure out which lua-raven package you're using, but the one in the official luarocks repo is ancient, and the one by cloudfare doesn't have any install instructions. Maybe you could update INSTALL.md in your branch? :)

**Comment by cycomachead** [comment]
Oh, can you `git submodule init`? (And then `ls lib/raven-lua`). 

Yeah, the luarocks cloud flare version is a mess, and Luarocks itself doesn't let you just clone a git repo....

You shouldn't need to install anything, because lib/raven-lua is a submodule, but I think you might need to re-run init. The problem is the way Lua handles LUA_PATH. 
https://github.com/snap-cloud/snapCloud/blob/master/lib/exceptions.lua#L27 is the line that tells Lua to look in the right spot for the module. There were some minor differences between macOS and Ubuntu on the server, so hopefully this covers the cases, but I think we can add more locations to the path if necessary.

**Comment by cycomachead** [comment]
@bromagosa I am going to merge this since Sentry is working and the rollbar code is no longer necessary. 
If there's still breaking issues locally, let's fix them. :)

**Comment by bromagosa** [comment]
Yup! It works now!

It's been so long since I could last run the cloud locally that my db is all messed up, though. I have a bit of work to do before I can go back to developing locally :)

Thanks!

**Pull request merged**
